
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.Label nom1;
	
	private global::Gtk.Label nom2;
	
	private global::Gtk.Label click;
	
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.Entry nom3;
	
	private global::Gtk.Entry nom4;
	
	private global::Gtk.Button unir;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TextView texto;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.nom1 = new global::Gtk.Label ();
		this.nom1.Name = "nom1";
		this.nom1.Xpad = 50;
		this.nom1.LabelProp = global::Mono.Unix.Catalog.GetString ("Nombre 1");
		this.hbox1.Add (this.nom1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.nom1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.nom2 = new global::Gtk.Label ();
		this.nom2.Name = "nom2";
		this.nom2.Xpad = 52;
		this.nom2.LabelProp = global::Mono.Unix.Catalog.GetString ("Nombre 2");
		this.hbox1.Add (this.nom2);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.nom2]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.click = new global::Gtk.Label ();
		this.click.Name = "click";
		this.click.Xpad = 3;
		this.click.LabelProp = global::Mono.Unix.Catalog.GetString ("Click para unir");
		this.hbox1.Add (this.click);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.click]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.nom3 = new global::Gtk.Entry ();
		this.nom3.CanFocus = true;
		this.nom3.Name = "nom3";
		this.nom3.IsEditable = true;
		this.nom3.InvisibleChar = '●';
		this.hbox3.Add (this.nom3);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.nom3]));
		w5.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.nom4 = new global::Gtk.Entry ();
		this.nom4.CanFocus = true;
		this.nom4.Name = "nom4";
		this.nom4.IsEditable = true;
		this.nom4.InvisibleChar = '●';
		this.hbox3.Add (this.nom4);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.nom4]));
		w6.Position = 1;
		// Container child hbox3.Gtk.Box+BoxChild
		this.unir = new global::Gtk.Button ();
		this.unir.CanFocus = true;
		this.unir.Name = "unir";
		this.unir.UseUnderline = true;
		this.unir.Label = global::Mono.Unix.Catalog.GetString ("Unir");
		this.hbox3.Add (this.unir);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.unir]));
		w7.Position = 2;
		w7.Expand = false;
		w7.Fill = false;
		this.vbox1.Add (this.hbox3);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.texto = new global::Gtk.TextView ();
		this.texto.CanFocus = true;
		this.texto.Name = "texto";
		this.GtkScrolledWindow.Add (this.texto);
		this.vbox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
		w10.Position = 2;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 424;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.unir.Clicked += new global::System.EventHandler (this.OnUnirClicked);
	}
}
